package com.weskaap.game.story;

public enum StoryFlag {
    ACT1_STARTED,
    HOUSE_ESTABLISHED,
    ELECTRICITY_PROBLEM_DISCOVERED,
    ELECTRICITY_RESTORED,
    FOOD_SHORTAGE_DISCOVERED,
    JOB_FOUND,
    FIRST_PAYCHECK_RECEIVED,
    CPUT_STARTED,
    BROKEN_CAR_REPAIRED,
    DOG_FOUND,
    SUPERNATURAL_MYSTERY_INTRODUCED,
    BROTHER_FOUND,
    BROTHER_THEFT_REVEALED,
    BROTHER_DEBT_DISCOVERED,
    TUBBY_PERSONAL_STORY_STARTED,
    ACT1_FAMILY_GATHERING_COMPLETED,
    ACT1_COMPLETED
}
